# Generated by Django 2.2.7 on 2019-11-27 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('ticketId', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('ticketName', models.CharField(max_length=200)),
                ('ticketDescription', models.TextField(max_length=10000)),
                ('ticketTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('condition', models.CharField(choices=[('Opened', 'Opened'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Opened', max_length=40)),
                ('priority', models.CharField(max_length=500)),
                ('staffmember', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=1000)),
                ('ticketId', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='ticket.Ticket', verbose_name='Ticket')),
                ('userId', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
        ),
    ]
