# Generated by Django 2.2.7 on 2019-11-29 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketId', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('ticketName', models.CharField(max_length=200)),
                ('ticketDescription', models.TextField(max_length=10000)),
                ('ticketTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.CharField(choices=[('Developer', 'Developer'), ('Tester', 'Tester'), ('Production', 'Production')], default='Developer', max_length=40)),
                ('condition', models.CharField(choices=[('Opened', 'Opened'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Opened', max_length=40)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=40)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=1000)),
                ('IdTicket', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='ticket.Ticket', verbose_name='Ticket')),
                ('user', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
        ),
    ]
