# Generated by Django 2.2.7 on 2019-11-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='role',
            field=models.CharField(choices=[('Developer', 'Developer'), ('Tester', 'Tester'), ('Production', 'Production')], default='Developer', max_length=40),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=40),
        ),
    ]
