# Generated by Django 2.2.7 on 2019-11-26 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=1000)),
                ('ticketId', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='ticket.Ticket', verbose_name='Ticket')),
                ('userId', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='Users')),
            ],
        ),
    ]
